reanahub/reana-workflow-controller

Dockerfile
MANIFEST.in
requirements.txt
setup.py

* Modifies Dockerfile accordingly. (closes #9)

installation: move requirements to setup.py

---

reana_workflow_controller/tasks.py

celery: fix broker service name

---

reana_workflow_controller/app.py
reana_workflow_controller/tasks.py
run-tests.sh

* Removes fibonacci endpoint and dependencies.
* Adds missing docstrings and plugs docstyle. (closes #8)

kwalitee: plug pydocstyle

---

docs/conf.py
docs/index.rst
docs/restapi.rst
reana_workflow_controller/app.py
setup.py

* Adds a new REST API chapter to the documentation.

docs: REST API chapter

---

Dockerfile
setup.py

docker: fix Dockerfile command for executing flask

---

Dockerfile

* Makes server publicly available.

docker: fix Dockerfile Flask cmd

---

MANIFEST.in
docs/conf.py
docs/openapi.json
docs/restapi.rst
reana_workflow_controller/rest.py
run-tests.sh
scripts/generate_openapi_spec.py
setup.py
tests/test_views.py

api: add openapi support

---

docs/openapi.json
reana_workflow_controller/factory.py
reana_workflow_controller/fsdb.py
reana_workflow_controller/models.py
reana_workflow_controller/multiorganization.py
reana_workflow_controller/rest.py
setup.py
tests/conftest.py
tests/test_views.py

db: move fsdb to sqlite

---

docs/openapi.json
reana_workflow_controller/rest.py
tests/test_views.py

* Arguments were in the wrong order causing the workspace to be created
wrongly.

api: fix workspace creation

---

reana_workflow_controller/fsdb.py
reana_workflow_controller/rest.py
tests/test_views.py

inputs: write input files to inputs directory

---

AUTHORS.rst
README.rst
docs/authors.rst
docs/changes.rst
docs/conf.py
docs/contributing.rst
docs/gettingstarted.rst
docs/index.rst
docs/introduction.rst
docs/license.rst
docs/restapi.rst

* Enhances documentation structure, updates author list, updates short
description and feature list.

docs: better structure

---

CHANGES.rst
reana_workflow_controller/version.py

release: v0.1.0

---

reana_workflow_controller/version.py

version: post-release bump

---

.gitignore
docs/openapi.json
reana_workflow_controller/app.py
reana_workflow_controller/cli.py
reana_workflow_controller/config.py
reana_workflow_controller/models.py
reana_workflow_controller/rest.py
reana_workflow_controller/tasks.py
tests/test_views.py

* Squashed version of https://github.com/reanahub/reana-workflow-controller/pull/53.

cwl: initial integration

---

docs/openapi.json
reana_workflow_controller/errors.py
reana_workflow_controller/rest.py
tests/test_views.py

* (closes reanahub/reana-client#75).

api: detect when workflow can not be started

---

docs/openapi.json
reana_workflow_controller/rest.py

@dinosk regarding https://github.com/reanahub/reana-server/pull/39#discussion_r173405666

openapi: standardize 404 error message

---

reana_workflow_controller/models.py

* ADDS unique constraint to Workflow model
(name, owner_id, run_number), and increases
the run_number manually.
(Closes https://github.com/reanahub/reana-workflow-controller/issues/72)
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>

rest: increase run_number manually

---

reana_workflow_controller/rest.py
tests/test_views.py

(Closes https://github.com/reanahub/reana-client/issues/87)

rest: REANA_WORKON mention in error message

---

AUTHORS.rst
CHANGES.rst
reana_workflow_controller/version.py

Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>

release: v0.2.0

---

AUTHORS.rst
reana_workflow_controller/version.py

docs: author ORCID links

---

reana_workflow_controller/rest.py
reana_workflow_controller/tasks.py

rest: addition of run_serial_workflow

---

docs/openapi.json
reana_workflow_controller/app.py
reana_workflow_controller/cli.py
reana_workflow_controller/config.py
reana_workflow_controller/rest.py
reana_workflow_controller/tasks.py
setup.py

* ADDS background task to consume message queue for job statuses.
(Contains https://github.com/reanahub/reana-workflow-controller/pull/83, so we could close it if we merge this)

global: receive messages from broker

---

reana_workflow_controller/rest.py
reana_workflow_controller/tasks.py

tasks: refactoring run progress recording

---

reana_workflow_controller/rest.py

rest: status current_command fixes

---

Dockerfile
reana_workflow_controller/cli.py
reana_workflow_controller/config.py
reana_workflow_controller/rest.py
reana_workflow_controller/tasks.py

* ADDS check for previous job status before
updating total counts for submitted|succeeded|failed
jobs.

tasks: accumulate progress reports

---

reana_workflow_controller/cli.py
reana_workflow_controller/config.py
reana_workflow_controller/consumer.py

* ADD consumer class with reconnection strategy based on
pika usage example: https://pika.readthedocs.io/en/latest/examples/blocking_consume_recover_multiple_hosts.html
Addresses #102 

global: addition of MQ consumer class

---

reana_workflow_controller/rest.py
reana_workflow_controller/utils.py
tests/test_views.py

Depends on https://github.com/reanahub/reana-commons/pull/30
Closes https://github.com/reanahub/reana-server/issues/58

global: renaming analyses to workflows

---

tests/conftest.py

Connects https://github.com/reanahub/reana-client/issues/128

tests: renaming api_token to access_token

---

docs/openapi.json
reana_workflow_controller/config.py
reana_workflow_controller/rest.py
reana_workflow_controller/utils.py
tests/conftest.py
tests/test_views.py

Connects https://github.com/reanahub/reana-commons/issues/25

global: remove organization

---

docs/openapi.json
reana_workflow_controller/rest.py

Closes https://github.com/reanahub/reana-client/issues/109

rest: optional parameters field

---

Dockerfile
docs/openapi.json
reana_workflow_controller/config.py
reana_workflow_controller/rest.py
reana_workflow_controller/tasks.py

Connect https://github.com/reanahub/reana-commons/issues/24
Depends on https://github.com/reanahub/reana-commons/pulls/34

rest: merge Workflow and Run table

---

docs/openapi.json
reana_workflow_controller/rest.py
reana_workflow_controller/utils.py

* Renames config variable since it no longer concerns workflows alone
but also files (closes reanahub/reana-client#162).

 rest: harmonise time format

---

CHANGES.rst
README.rst
reana_workflow_controller/version.py

release: v0.3.1

---

Dockerfile
reana_workflow_controller/cli.py
reana_workflow_controller/consumer.py
setup.py

consumer: use Kombu based consumer

---

docs/conf.py
docs/requirements.txt
docs/restapi.rst
run-tests.sh
setup.py

* Improves REST API docs rendering. Closes reanahub/reana#25

docs: improve sphinxcontrib-openapi rendering

---

AUTHORS.rst
CHANGES.rst
reana_workflow_controller/consumer.py
reana_workflow_controller/version.py
setup.py

release: v0.4.0

---

docs/openapi.json
reana_workflow_controller/rest.py
setup.py
tests/test_views.py

* Introduces new endpoint which returns workflow parameters.
Connects https://github.com/reanahub/reana-client/issues/200

api: workflow parameters

---

reana_workflow_controller/rest.py
tests/test_utils.py

* Includes WorkflowStatus.stopped in statuses allowing deletion.

rest: allow deletion of stopped workflows

---

docs/openapi.json
reana_workflow_controller/rest.py
reana_workflow_controller/utils.py
scripts/generate_openapi_spec.py
tests/test_utils.py
tests/test_views.py

* (Close reanahub/reana-client#210).
Blocked by https://github.com/reanahub/pytest-reana/pull/34.

api: add delete file endpoint

---

docs/openapi.json
reana_workflow_controller/rest.py
run-tests.sh
setup.py
tests/test_views.py

* Adds get_workflow_diff method to return
differences between the assets of two workflows.
Connects https://github.com/reanahub/reana-client/issues/193
Depends on https://github.com/reanahub/pytest-reana/pull/35

rest: addition of workflow diff

---

reana_workflow_controller/workflow_run_managers/__init__.py
reana_workflow_controller/workflow_run_managers/kubernetes/__init__.py
setup.py

Connects reanahub/reana-workflow-engine-serial#5

workflow execution: pass arguments to rwe_ individual runs

---

reana_workflow_controller/workflow_run_managers/__init__.py

* Connects reanahub/reana-workflow-engine-yadage/issues/94

workflow execution: pass arguments to rwe_yadage individual runs

---

reana_workflow_controller/workflow_run_managers/__init__.py

* Allows to create CWL workflow engine on demand.
Connects reanahub/reana-workflow-engine-cwl/issues/75

global: serverless CWL workflow engine

---

reana_workflow_controller/config.py
reana_workflow_controller/consumer.py
reana_workflow_controller/errors.py
reana_workflow_controller/rest.py
tests/test_views.py

* Refactors instantiation of JobStatusConsumer to new message queue
configuration in reana-commons.
* Removes deprecated configuration.
Connects https://github.com/reanahub/reana/issues/119

config: refactor message queue configuration

---

Dockerfile
reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py
setup.py

Connects https://github.com/reanahub/reana-cluster/issues/131 

config: set SHARED_VOLUME_PATH to /var/reana

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

Connects https://github.com/reanahub/reana-cluster/issues/142.

workflow-execution: configurable engine versions

---

reana_workflow_controller/utils.py
tests/test_utils.py

* Closes reanahub/reana-workflow-engine-serial/issues/64

utils: path fix for cached workspace

---

docs/openapi.json
reana_workflow_controller/rest.py

* Connects reanahub/reana-client/issues/213

api: new endpoint for mv files command

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

Connects https://github.com/reanahub/reana-cluster/issues/154

config: refactor workflow engine image vars

---

docs/openapi.json
reana_workflow_controller/rest.py
setup.py

Connect https://github.com/reanahub/reana-client/issues/238

rest: disk usage for workflows

---

reana_workflow_controller/templates/k8s/interactive-deployment.template
reana_workflow_controller/workflow_run_manager.py
setup.py

interactive-execution: protect interactive session

---

reana_workflow_controller/workflow_run_manager.py

* List of CVMFS repos is provided as dict, not as a list.
Connects reanahub/reana-client/issues/256

cvmfs: passing list of repos

---

reana_workflow_controller/k8s.py
reana_workflow_controller/utils.py
reana_workflow_controller/workflow_run_manager.py

interactive-execution: add REANA shared storage

---

reana_workflow_controller/utils.py
setup.py
tests/test_utils.py

* Connects reanahub/reana-workflow-engine-cwl/issues/90

utils: Setting umask 002 before worspace creation

---

Dockerfile

docker: slimmer image

---

AUTHORS.rst
CHANGES.rst
README.rst
docs/conf.py
docs/openapi.json
reana_workflow_controller/cli.py
reana_workflow_controller/config.py
reana_workflow_controller/factory.py
reana_workflow_controller/k8s.py
reana_workflow_controller/rest.py
reana_workflow_controller/utils.py
reana_workflow_controller/version.py
reana_workflow_controller/workflow_run_manager.py
run-tests.sh
setup.py
tests/test_views.py
tests/test_workflow_run_manager.py

* Closes #208
* Fix import sorting to uncomment isort in run_test.py.
* Fix docs badge link (Closes reanahub/reana#162)
* Fix kubernetes dependency conflict (Closes #210)
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

release: 0.5.0

---

reana_workflow_controller/config.py
reana_workflow_controller/tasks.py
reana_workflow_controller/workflow_run_manager.py
setup.py

* Run RJC and RWE in the same pod.
Connects reanahub/reana-job-controller/issues/105

workflow_run_manager: RJC & RWE as a sidecar

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

workflow_run_manager: shortens RWE container name

---

reana_workflow_controller/tasks.py

* Closes reanahub/reana-job-controller/issues/150

tasks: fixes job progress calculation

---

reana_workflow_controller/workflow_run_manager.py

* Before all the secrets, regardless of their type, were mounted as files
* Closes #222
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

secrets: mount only file-type secrets

---

reana_workflow_controller/workflow_run_manager.py
setup.py

* Closes #221
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

secrets: extract secret manipulation code to r-commons

---

AUTHORS.rst
Dockerfile
docs/openapi.json
reana_workflow_controller/config.py
reana_workflow_controller/consumer.py
reana_workflow_controller/rest.py
reana_workflow_controller/utils.py
setup.py

Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>

api: create workflow from gitlab project

---

reana_workflow_controller/workflow_run_manager.py

* Creates group before adding user.
Closes #247

workflow_run_manager: creates group

---

reana_workflow_controller/workflow_run_manager.py

* Removes groupadd warning in RJC.
Closes #260

workflow_run_manager: removes warning in RJC

---

reana_workflow_controller/consumer.py

Tested successfully with `helloworld` and `worldpopulation` demos.
Related to https://github.com/reanahub/reana-cluster/pull/240
Addresses #249

consumer: add http prefix

---

Dockerfile
reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py
setup.py

workflow_run_manager: refactors volume mounts

---

reana_workflow_controller/consumer.py
reana_workflow_controller/rest.py
setup.py

addresses reanahub/reana-server#177

consumer: use git_repo to update commit status

---

reana_workflow_controller/rest.py
reana_workflow_controller/workflow_run_manager.py
tests/test_workflow_run_manager.py

* Closes reanahub/reana-client/issues/310

workflow_run_manager: does not return closed sessions to cli

---

reana_workflow_controller/workflow_run_manager.py

config: add REANA prefix to components

---

docs/openapi.json
reana_workflow_controller/rest.py
setup.py

addresses reanahub/reana-client#341

api: pass block size param to get disk usage

---

reana_workflow_controller/utils.py

gitlab: decrease depth when cloning project

---

reana_workflow_controller/rest.py

* Closes reanahub/reana-client/issues/348

rest: logs endpoing returns more information about the job

---

reana_workflow_controller/rest/utils.py

* Addresses reanahub/reana-client/issues/355

rest-utils: allows to restart workflow

---

reana_workflow_controller/consumer.py

* Properly saves run_finished_at attribute

consumer: does a commit to DB on every message

---

docs/openapi.json
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_status.py
setup.py
tests/test_views.py

* Addresses reanahub/reana-client/issues/369

rest: adds a possibility to query logs for a given step

---

reana_workflow_controller/errors.py
reana_workflow_controller/workflow_run_manager.py
setup.py
tests/conftest.py

* Reads job status from Job table, to get the running jobs
(closes reanahub/reana#266).

status: retrieve job status from Job table

---

reana_workflow_controller/k8s.py
reana_workflow_controller/workflow_run_manager.py
setup.py

workflow-run-manager: mount CVMFS on int. sessions

---

reana_workflow_controller/consumer.py

* Closes reanahub/reana-workflow-engine-serial/issues/103

consumer: does not override workflow logs

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

* Closes reanahub/reana-job-controller#230.

config: load configured image pull secrets

---

reana_workflow_controller/rest/utils.py

closes reanahub/reana-client#388

cli: diff operational parameters properly

---

reana_workflow_controller/config.py
reana_workflow_controller/k8s.py
reana_workflow_controller/workflow_run_manager.py

* Closes reanahub/docs.reana.io#18.

workflow-run-manager: pass component prefix to wf

---

reana_workflow_controller/config.py
reana_workflow_controller/rest/workflows.py
run-tests.sh
setup.py
tests/conftest.py
tests/test_utils.py
tests/test_views.py

partially addresses reanahub/reana#348
depends on reanahub/pytest-reana#63 reanahub/reana-db#73

tests: move to containerised postgres DB

---

reana_workflow_controller/k8s.py
reana_workflow_controller/workflow_run_manager.py
setup.py

* If there is a configured node label to use as nodeSelector
RWC will use it so the RWE's pods get scheduled to those nodes.

workflow-run-manager: use node selector for RWE's

---

reana_workflow_controller/workflow_run_manager.py

* Adds [accidentally removed line which adds the user secrets
to the RJC container](https://github.com/reanahub/reana-workflow-controller/pull/324/files#diff-34e7069f4920280582191829f586c0a9L505).

workflow-run-manager: add secrets to RJC

---

reana_workflow_controller/rest/workflows.py
reana_workflow_controller/workflow_run_manager.py
tests/test_workflow_run_manager.py

closes https://github.com/reanahub/reana-ui/issues/77

rest: return interactive sessions on verbose workflows request

---

docs/openapi.json
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_status.py
tests/test_utils.py
tests/test_views.py

closes reanahub/reana-client#436

rest: get rid of workflow hard deletion

---

CHANGES.rst
reana_workflow_controller/rest/workflows_workspace.py
requirements.txt
setup.py

api: recalculate quota on file upload/deletion

---

.flake8
.github/workflows/ci.yml
Dockerfile
MANIFEST.in
reana_workflow_controller/consumer.py
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows.py
reana_workflow_controller/rest/workflows_workspace.py
run-tests.sh
setup.py
tests/test_views.py
tests/test_workflow_run_manager.py

addresses https://github.com/reanahub/reana/issues/450

ci: add hadolint and flake8 linters

---

CHANGES.rst
docs/openapi.json
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_workspace.py
tests/test_utils.py
tests/test_views.py

Depends on https://github.com/reanahub/reana-workflow-controller/pull/366
closes reanahub/reana-client#402

rest: support dir and glob patterns download

---

reana_workflow_controller/k8s.py
reana_workflow_controller/workflow_run_manager.py

Closes reanahub/reana#493.
CI blocked by https://github.com/reanahub/reana-commons/pull/257 release.

k8s: set specific node label for batch workflows

---

CHANGES.rst
reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

closes reanahub/reana-client#496

config: configurable max user-custom job memory limits

---

CHANGES.rst
reana_workflow_controller/config.py
reana_workflow_controller/consumer.py
reana_workflow_controller/rest/utils.py

Closes reanahub/reana-client#497.

rest: add job start and finish times

---

docs/openapi.json
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows.py
reana_workflow_controller/rest/workflows_status.py
requirements.txt
setup.py

performance optimisations for list command
closes https://github.com/reanahub/reana-client/issues/510

list: add --include-progress and --include-workspace-size

---

reana_workflow_controller/rest/utils.py

closes https://github.com/reanahub/reana-client/issues/520

fix: add raw and human_readable format in size object

---

docs/openapi.json
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows.py
reana_workflow_controller/rest/workflows_workspace.py

- api: add search type in /workspace
closes https://github.com/reanahub/reana-client/issues/521

Add search param in get_files

---

docs/openapi.json
reana_workflow_controller/version.py
requirements.txt
setup.py

release: 0.8.0a2

---

reana_workflow_controller/rest/utils.py
requirements.txt
setup.py

closes https://github.com/reanahub/reana-client/issues/522

utils: move wildcard pattern functionality to r-commons

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

closes reanahub/reana-client#531

workflow-run-manager: support snakemake

---

reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_workspace.py

closes https://github.com/reanahub/reana-client/issues/536

rest: improve downloaded tarballs name

---

AUTHORS.rst
docs/openapi.json
reana_workflow_controller/k8s.py
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows.py
reana_workflow_controller/rest/workflows_workspace.py
reana_workflow_controller/workflow_run_manager.py
requirements.txt
setup.py
tests/test_utils.py
tests/test_views.py

Quit the dependency of upload-file,remove-file, list-files,mv-files and download, relying directly on the full-path stored in the database
Closes reanahub/reana-db#94

models: modify workspace_path to store full path

---

reana_workflow_controller/workflow_run_manager.py

workflow_run_manager: add MOUNTED_PATHS as env variable in the run-batch pods

---

docs/openapi.json
reana_workflow_controller/rest/workflows.py

Closes reanahub/reana-client#452

workflows: filter workflows listed using -w workflow passed

---

reana_workflow_controller/config.py
reana_workflow_controller/rest/utils.py
setup.py
tests/test_utils.py

* refactor code to make it more readable
* add tests covering mime type guessing
closes reanahub/reana-ui#190

rest: support html as previewable mime type

---

reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_workspace.py

workspace: improve file search logic

---

reana_workflow_controller/consumer.py

- separate deletion of workflow job and saving workflow engine pod logs, so workflow engine logs are captured even if workflow job is not deleted.
closes #426
closes reanahub/reana-workflow-engine-snakemake#35
1. Try to reproduce the issue, it should not be possible.

job status consumer: fix workflow engine logs when job is not deleted

---

CHANGES.rst
reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

closes reanahub/reana-job-controller#343

config: add kubernetes jobs timeout env variables

---

CHANGES.rst
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows.py

closes https://github.com/reanahub/reana-ui/issues/229

rest: improve filtering by workflow in get workflows endpoint

---

CHANGES.rst
reana_workflow_controller/rest/workflows_status.py
tests/test_views.py

return error if workflow is deleted without workspace

---

CHANGES.rst
reana_workflow_controller/factory.py
reana_workflow_controller/rest/workflows.py
tests/test_views.py

rest: correctly parse boolean query parameters in `get_workflows`

---

CHANGES.rst
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_workspace.py
tests/test_utils.py

rest: allow moving files while workflow is running

---

requirements.txt
setup.py
tests/test_utils.py
tests/test_views.py

Closes reanahub/reana-commons#379

rest: support recursive globbing in workspace endpoints

---

reana_workflow_controller/consumer.py
reana_workflow_controller/rest/utils.py

Closes reanahub/reana-client#646

rest: avoid returning null job id in workflow progress

---

reana_workflow_controller/rest/workflows_workspace.py
tests/test_views.py

rest: return 404 when listing files of a deleted workflow

---

CHANGES.rst
reana_workflow_controller/rest/utils.py
requirements.txt
scripts/generate_openapi_spec.py
setup.py
tests/test_utils.py

closes https://github.com/reanahub/reana-client/issues/649

rest: improve deletion of workflows with attached interactive sessions

---

CHANGES.rst
reana_workflow_controller/config.py

Addresses reanahub/reana-ui#78.

config: add application/pdf to the supported MIME types for file preview.

---

docs/openapi.json
reana_workflow_controller/version.py
requirements.txt
setup.py

- installation: bump shared modules
- release: 0.9.1a2

release 0.9.1a2

---

CHANGES.rst
reana_workflow_controller/rest/utils.py

utils: add run_stopped_at to workflow progress info

---

.github/codecov.yml
Dockerfile
reana_workflow_controller/config.py
run-tests.sh

Adds fully qualified canonical locations of container images, making the container technology setup podman-friendly.
Closes reanahub/reana#729.

docker: podman-friendly image locations

---

CHANGES.rst
docs/openapi.json
reana_workflow_controller/version.py
requirements.txt
setup.py

- installation: bump shared modules
- installation: bump all dependencies
- release: 0.9.1

release: 0.9.1

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

- feat(manager): pass custom env variables to workflow engines (#571)
- feat(manager): pass custom env variables to job controller (#571)

feat(manager): pass custom env variables to workflow engines and job controller (#571)

---

.github/workflows/ci.yml
AUTHORS.md
reana_workflow_controller/config.py
reana_workflow_controller/k8s.py
reana_workflow_controller/rest/workflows_session.py
reana_workflow_controller/workflow_run_manager.py
run-tests.sh
tests/test_k8s.py
tests/test_views.py
tests/test_workflow_run_manager.py

* feat(helm): allow cluster administrator to configure ingress host (#588)
* ci(commitlint): improve checking of merge commits (#590)

chore(master): merge maint-0.9

---

reana_workflow_controller/workflow_run_manager.py

fix(manager): reduce size of job-controller's db connection pool (#594)

---

reana_workflow_controller/k8s.py
reana_workflow_controller/rest/workflows.py

fix(k8s): check readiness of Dask service pods

---

.commitlintrc.yaml
reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py
requirements.txt
setup.py

Pass the following env variables to job controller
- `REANA_KUBERNETES_JOBS_CPU_REQUEST`
- `REANA_KUBERNETES_JOBS_CPU_LIMIT`
- `REANA_KUBERNETES_JOBS_MEMORY_REQUEST`
- `REANA_KUBERNETES_JOBS_MEMORY_LIMIT`
Closes reanahub/reana#883

feat(manager): pass k8s resource env variables to job controller

---

.editorconfig
.github/workflows/ci.yml
AUTHORS.md
MANIFEST.in
run-tests.sh

- Adds shfmt 
Closes https://github.com/reanahub/reana-workflow-controller/issues/652

 ci(shfmt): add shfmt code formatting checks (#654)
