reanahub/reana-workflow-controller

CONTRIBUTING.rst
README.rst
docs/conf.py
docs/contributing.rst
docs/gettingstarted.rst
docs/index.rst
docs/introduction.rst
docs/requirements.txt
docs/usage.rst

* Adds more documentation chapters (Introduction, Getting started,
Contributing).
* Adds Travis/Coveralls/RFTD/Waffle/Travis/License badges.
* Adds `docs/requirements.txt` so that ReadTheDocs can install all the
prerequisites for building the autodoc parts of the documentation.

docs: structure improvements and new chapters

---

docs/restapi.rst
reana_workflow_controller/app.py

* Add MOCKED /workflows -endpoint that provides a quick way to
check if reana-workflow-engine is running. Closes #20.
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

api: Add MOCKED /workflows -endpoint

---

docs/openapi.json
reana_workflow_controller/rest.py

api: accept workflow specifications instead of toplevel+workflow name

---

docs/openapi.json
reana_workflow_controller/rest.py
scripts/generate_openapi_spec.py

api: add workflow seeding endpoint

---

docs/openapi.json
reana_workflow_controller/fsdb.py
reana_workflow_controller/models.py
reana_workflow_controller/rest.py
tests/conftest.py
tests/test_views.py

* (Closes reanahub/reana-workflow-engine-yadage#32)

api: add initialize workflow endpoint

---

reana_workflow_controller/rest.py

* (closes reanahub/reana-server#13).

api: fix path to write input files

---

docs/openapi.json
reana_workflow_controller/fsdb.py
reana_workflow_controller/rest.py
tests/test_views.py

* Removes REANAFS singleton since it was making tests complicated.
* (addresses #38).

api: add endpoint to retrieve output files

---

docs/openapi.json
reana_workflow_controller/config.py
reana_workflow_controller/fsdb.py
reana_workflow_controller/rest.py
tests/test_views.py

* (addresses reanahub/reana-client#40).

api: add listing input files endpoint

---

docs/openapi.json
reana_workflow_controller/config.py
reana_workflow_controller/rest.py
tests/test_views.py

api: add listing output files endpoint

---

docs/openapi.json
reana_workflow_controller/rest.py
tests/test_views.py

* add endpoint for getting status of a workflow
(closes reanahub/reana-client#39)
* (Closes https://github.com/reanahub/reana-workflow-controller/pull/44).

api: add endpoint for workflow status

---

docs/openapi.json
reana_workflow_controller/rest.py
tests/test_views.py

For prior discussion see: https://github.com/reanahub/reana-workflow-controller/pull/50

api: add endpoint to set status of an analysis

---

reana_workflow_controller/rest.py

* Since workflow engines have already mounted the corresponding
organization directory, workflow_workspace should not contain it.

tasks: remove organization from workflow_workspace

---

docs/openapi.json
reana_workflow_controller/config.py
reana_workflow_controller/errors.py
reana_workflow_controller/models.py
reana_workflow_controller/rest.py
tests/conftest.py
tests/test_views.py

* Add support for specifying a name for workflow run
(closes reanahub/reana-client#70)
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

api: support specifying workflow run name

---

reana_workflow_controller/rest.py

* FIXES querying for workflow statuses when specifying
the workflow name and the run number.
(Addresses https://github.com/reanahub/reana-workflow-controller/issues/72)
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>

api: fix querying for workflow status

---

reana_workflow_controller/errors.py
reana_workflow_controller/rest.py

* FIXES formatting of the paths that are created
from uploading files or directories to a workflow.
(Closes https://github.com/reanahub/reana-client/issues/67)

rest: upload files and dirs to workflow fixes

---

reana_workflow_controller/utils.py

* When `fs` module is imported it does not contain the path module,
it has to be imported explicitly. This causes a rare case when,
if in the scope the instruction `from fs import path` is executed
then `path` is added to the `fs` object otherwise an AttributeError
exception will be thrown (closes reanahub/reana-client#113).

utils: explicitly import fs.path

---

Dockerfile

* Adds `--wsgi-disable-file-wrapper` flag since send_file and hence
send_fron_directory do not work with `uwsgi` file wrapper (known
issue https://github.com/unbit/uwsgi/issues/1126).

docker: disable uwsgi file wrapper

---

reana_workflow_controller/cli.py
reana_workflow_controller/consumer.py
reana_workflow_controller/tasks.py

depends on https://github.com/reanahub/reana-commons/pull/22, https://github.com/reanahub/reana-cluster/pull/93, https://github.com/reanahub/reana-commons/pull/29
Closes https://github.com/reanahub/reana-job-controller/issues/76

global: receive and store job caching info

---

docs/openapi.json
reana_workflow_controller/config.py
reana_workflow_controller/rest.py
reana_workflow_controller/tasks.py
reana_workflow_controller/utils.py
tests/test_views.py

* Seed workflow run workspace instead per type (inputs/outputs/code).
Closes #107.
Depends on https://github.com/reanahub/reana-commons/pull/28.

rest: unify inputs/outputs/code to single dir

---

docs/openapi.json
reana_workflow_controller/rest.py
tests/test_views.py

* ADD parameters object in set_workflow_status to pass arbitrary
number of parameters to a workflow run.
Connects https://github.com/reanahub/reana-client/issues/143

rest: parameters object in set_workflow_status

---

reana_workflow_controller/rest.py

* Since we are interpolating user provided commands with their
parameters (expanding any occurrence of $varname or ${varname}
with the values provided as workflow parameters, we can not
mix workflow params, those to be populated into the commands,
and engine parameters, those to be passed to the engines to behave
is supported and checked for correctness.
differently (closes reanahub/reana-workflow-engine-serial#34).

tasks: split workflow params from engine params

---

reana_workflow_controller/tasks.py

* Removes condition connecting file access times and input
identification. All files that are present before a step starts,
are included in the workspace hash calculation.

tasks: file selection for workspace hash

---

reana_workflow_controller/rest.py
setup.py
tests/test_views.py

* Replaces celery tasks running workflows with Mock objects, and
asserts that the right arguments are passed.
Depends on https://github.com/reanahub/reana-db/issues/12
Closes https://github.com/reanahub/reana-workflow-controller/issues/132

tests: celery task mocking

---

Dockerfile
docs/openapi.json
reana_workflow_controller/rest.py
reana_workflow_controller/tasks.py
setup.py
tests/test_views.py

* Finalises workflow execution through revoke method (which is going
to kill the process in which the task was running).
Connect reanahub/reana-client#194.
Blocked by https://github.com/reanahub/pytest-reana/pull/26.

tasks: add stop option

---

reana_workflow_controller/workflow_run_managers/__init__.py

* Enables wdb for serverless workflows.
Closes reanahub/reana-workflow-engine-cwl/issues/79

global: enable wdb

---

setup.py

* Adding include_package_data=True to setup.py, which allows
to include package subfolders. Closes #160

setup: Fix for broken dependencies

---

reana_workflow_controller/workflow_run_managers/__init__.py

* Encoding json flag values that are passed to WFEs, to be
bash valid. Closes #167

cli: encoding json flag values

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_managers/kubernetes/__init__.py

* Setting ttl_seconds_after_finished = 60, to delete completed
pods. Closes reanahub/reana-workflow-engine-serial/issues/58

k8s: delete completed pods

---

reana_workflow_controller/rest.py
reana_workflow_controller/workflow_run_manager.py
setup.py
tests/test_views.py

* Uses utility methods from r-commons to create persistent volume
claims and storage classes that might not be present in the
cluster, based on running workflow resource requirements.
Connect https://github.com/reanahub/reana-cluster/issues/154

workflow_run_manager: CVMFS pvc and sc creation

---

docs/openapi.json
reana_workflow_controller/version.py
reana_workflow_controller/workflow_run_manager.py
setup.py

* Adds check for unknown cvmfs volumes before attempting to create
them via the k8s api.

workflow_run_manager: fix mounting unknown volumes

---

docs/openapi.json
reana_workflow_controller/k8s.py
reana_workflow_controller/rest.py
reana_workflow_controller/workflow_run_manager.py
tests/test_views.py

* Makes k8s objects created for an interactive session dependent.
If ingress object gets deleted, service and deployment objects
are deleted automaticallyi.
Closes reanahub/reana-client/issues/247

k8s: dependent interactive objects

---

reana_workflow_controller/config.py

* Removes r-w-monitor and zeromq cluster components that were not used since
many moons. Helps to make the cluster slimmer and faster.
(connects reanahub/reana-cluster#169)

global: removal of r-w-monitor and zeromq

---

reana_workflow_controller/workflow_run_manager.py

* fix wrong number of positional arguments exception
* Closes reanahub/reana-client#291
* Same problem as in reanahub/reana-job-controller/pull/128
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

cli: fix stop command exception

---

reana_workflow_controller/workflow_run_manager.py
setup.py
tests/test_views.py

* addresses reanahub/reana-job-controller#147

secrets: pass reana user id to workflow engines

---

reana_workflow_controller/workflow_run_manager.py

workflow_run_manager: mount only db + workspace

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py
setup.py

* REANA_STORAGE_BACKEND is being centrally loaded by REANA-Commons since
all REANA components should be deployed with the same storage backend.

config: remove REANA_STORAGE_BACKEND config

---

reana_workflow_controller/workflow_run_manager.py

* In the case of CEPHFS there is no hostPath available to
retrieve the root path, leading to a KeyError exception.
Instead we get the root path from the globally configured
`SHARED_VOLUME_PATH` variable (configured by REANA-Cluster).

volumes: fix root path

---

setup.py

* Unpins urllib3 since it is correctly set as a dependency in the
Python Kubernetes client (addresses reanahub/reana-client#320).

installation: unpin urllib3

---

reana_workflow_controller/consumer.py

consumer: removes unused task

---

reana_workflow_controller/utils.py

closes reanahub/reana-client#312

cli: skip unresolvable symlinks when listing files

---

docs/openapi.json
reana_workflow_controller/rest.py
tests/test_views.py

* After the findings in
https://github.com/diegodelemos/client-server-flask-big-file-uploads
it is clear we have to move from multipart uploads to stream uploads
using `request.stream` directly (closes reanahub/reana-client#302).

api: stream file uploads using request.stream

---

reana_workflow_controller/consumer.py

This reverts commit 441e28b905ef21d33abc2fe5f1972b42f14f7f12.
* We are correctly using the
[TTLSecondsAfterFinished](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished),
and it really works, but the subtle detail is that RJC never
finishes. One can see this by checking how many ready containers
are inside the pod, Workflow Engine finishes and RJC still runs,
see:
```console
$ kubectl get pod \
batch-serial-a0f3f1c4-161d-461c-94e0-c4dae1000b2f-nv8bb -o json | \
jq '.status.containerStatuses[] | .name + " " + (.ready|tostring)'
"job-controller true"
"workflow-engine false"
```
Because of this we need to manually delete the batch- containers
with the task that was removed in the previous commit
(closes #258).

Revert "consumer: removes unused task"

---

reana_workflow_controller/k8s.py
setup.py
tests/test_views.py
tests/test_workflow_run_manager.py

k8s: fixes after k8s upgrade

---

reana_workflow_controller/workflow_run_manager.py

* Addresses https://github.com/reanahub/reana-job-controller/issues/71

workflow_run_manager: renames HTCONDORCERN_USERNAME to CERN_USERNAME

---

reana_workflow_controller/consumer.py
reana_workflow_controller/workflow_run_manager.py
setup.py

* From a deployment phase (instantiation of the REANA cluster with
`reana-cluster init`) the admin tells if EOS is available in the
underlying Kubernetes cluster. RWC receives this information from
the environment and passes it over to RJC, which is instantiated
on demand. It is interesting to have this information here since
RWC instantiates also interactive sessions which could benefit
also from mounting EOS (closes reanahub/reana#216).

workflow_run_manager: tell RJC if EOS is available

---

reana_workflow_controller/k8s.py
reana_workflow_controller/workflow_run_manager.py
tests/test_views.py
tests/test_workflow_run_manager.py

* Extensions API gets will get deprecated Ingressses this commit
switches to the new Networking API.
* Change deletion of Deployments to use `apps` API which was missing
in the Kubernetes 1.16 upgrade (closes #267).

k8s: use apps and networking APIs

---

reana_workflow_controller/workflow_run_manager.py

* Addresses reanahub/reana-workflow-controller/issues/269

workflow_run_manager: changes workspace group

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

* Adds REANA code mounted to runtime pods (RWE_ and RJC) when
FLASK_ENV is `development`. We assume that when REANA is installed
in dev mode, minikube will have all REANA source code under `/code`
this safe to assume since it is part of our Makefile procedures
(we do not allow to run REANA in dev mode without the mount active).

workflow_run_manager: add code mount in dev mode

---

docs/openapi.json
reana_workflow_controller/errors.py
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_status.py
reana_workflow_controller/workflow_run_manager.py
tests/test_views.py

workflow_run: notify about third party failures

---

reana_workflow_controller/workflow_run_manager.py

* There will be cases (i.e. integration with Git providers) in
which there won't be a workflow specification stored in the
database. This only happens when a submission doesn't come from a REANA
client. So in these cases, by knowing the path of the workflow
file, the workflow engines can load with their specific libraries
the workflow files (which we will optimistically assume are there
if not, workflow engine should fail saying there is no workflow
to be processed) (closes reanahub/reana#235).

workflow_run_manager: pass workflow file if exists

---

reana_workflow_controller/config.py
reana_workflow_controller/workflow_run_manager.py

* A new label is added to batch workflow runs. This allows to do a
search for all batch workflows running in REANA used to limit
the number of workflows running in a REANA cluster. This could be
used for monitoring (creating filters in Grafana) and accounting.

workflow_run_manager: add batch workflow label

---

.travis.yml
reana_workflow_controller/consumer.py
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows.py
reana_workflow_controller/rest/workflows_workspace.py
reana_workflow_controller/workflow_run_manager.py
setup.py
tests/test_utils.py
tests/test_views.py

* It allows reuse of workspace.
* Addresses reanahub/reana-workflow-controller/issues/289

global: changes get_workspace method with workspace_path field

---

reana_workflow_controller/rest/workflows.py
setup.py

* `true` and `false` when passed to `bool()` are always true
(closes reanahub/reana-client#367).

rest: load json boolean

---

reana_workflow_controller/errors.py
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_status.py

* Closes reanahub/reana-client/issues/239

rest: allows to delete queued workflows

---

docs/openapi.json
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows.py
reana_workflow_controller/rest/workflows_status.py
tests/test_views.py

rest: return workflow progress

---

docs/openapi.json
reana_workflow_controller/rest/workflows_workspace.py
setup.py

rest: add preview flag to download file

---

reana_workflow_controller/rest/workflows.py
reana_workflow_controller/workflow_run_manager.py

closes reanahub/reana-client#396
reana.yaml could be like:
```yaml
version: 0.6.0
[...]
workflow:
type: yadage
file: workflow.yaml
options: 
initdir: ./myinitdir
[...]
```

yadage: allow passing initdir configuration

---

reana_workflow_controller/config.py
reana_workflow_controller/consumer.py
reana_workflow_controller/workflow_run_manager.py

* Happening when user stops a workflow before its first job is created.
RWC stops only the existing jobs. However, because there is a grace
period for stopping pods, RJC sidecar still runs, submitting a new
job, and reporting its status, causing the workflow to “revive”
(closes reanahub/reana-client#395).

workflow_run_manager: workflow stop race condition

---

CHANGES.rst
reana_workflow_controller/consumer.py
reana_workflow_controller/workflow_run_manager.py

* In order to be able to deploy REANA in different Kubernetes
namespaces we use the centrally configured variable from
REANA-Commons which represents it. This configuration happens
at deployment time (closes reanahub/reana#274).
* Creates REANA runtime objects in the configured runtime namespace.
Note that if no runtime namespace is configured by default it will
be the same as the infrastructure pods namespace
(closes reanahub/reana#268).

config: use centrally configured k8s namespace

---

reana_workflow_controller/config.py
reana_workflow_controller/consumer.py

Renames `REANA_URL` to a more precise `REANA_HOSTNAME` everywhere in
the code base.
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

config: REANA_URL -> REANA_HOSTNAME

---

reana_workflow_controller/rest/workflows.py

When deleting a workflow via `reana-client delete -w my_wf --include-workspace`,
the workspace folder is deleted and retriving workflow size via e.g. `reana-client
list -v` failed.
closes reanahub/reana-ui#129

rest: fix retrieving size of deleted workflows

---

reana_workflow_controller/consumer.py
reana_workflow_controller/rest/utils.py
requirements.txt
setup.py

* Let REANA-DB atomically manage status change related operations.
For example, setting the finished/stopped/failed time (removed
from RWC in this PR), updating quota usage etc...
Closes reanahub/reana-workflow-controller#332.

models: REANA-DB to manage workflow status change

---

CHANGES.rst
reana_workflow_controller/config.py
reana_workflow_controller/consumer.py
reana_workflow_controller/workflow_run_manager.py
requirements.txt
setup.py

* Addresses reanahub/reana#461.
* Removes TTLAfterFinished config since this doesn't work with workflow
engines because there is RJC as sidecar, and it never completes its execution
(Flask application). Two solutions were quickly evaluated which either aren't
too robust or they don't fit into current planning:
- New endpoint `/shutdown` in RJC, called by RWE when workflow ends
- The only way found to implement is to explicitly through `RuntimeError`
inside `/shutdown`, which would make the workflow pod fail.
- Share folder between containers, write flag to file when workflow finishes.
- Too convoluted and no time to test thoroughly since we have a workshop
next week.

global: configurable job cleanup

---

reana_workflow_controller/workflow_run_manager.py
tests/test_utils.py

* Allows workflow stop operation to finalise even if Kubernetes
call to stop the workflow jobs and its jobs fails. An error is
logged so administrators can see it and clean up the cluster
accordingly (closes reanahub/reana-client#360).
To test:
1. Comment the following code in REANA-Commons:
```diff
diff --git a/reana_commons/workflow_engine.py b/reana_commons/workflow_engine.py
index 51bceb2..692fcad 100644
--- a/reana_commons/workflow_engine.py
+++ b/reana_commons/workflow_engine.py
@@ -170,7 +170,7 @@ def create_workflow_engine_command(
)
try:
-            signal.signal(signal.SIGTERM, exit_handler or _default_exit_handler)
+            # signal.signal(signal.SIGTERM, exit_handler or _default_exit_handler)
publisher = WorkflowStatusPublisher()
rjc_api_client = …
```

utils: fix stop workflow

---

reana_workflow_controller/consumer.py
reana_workflow_controller/rest/utils.py
tests/test_utils.py
tests/test_views.py

closes https://github.com/reanahub/reana-workflow-controller/issues/363
Depends on https://github.com/reanahub/reana-db/pull/123 (tests fail because `pending` status is not present yet)
* Sets workflow status to `pending` right after the workflow has been started
* ~~Adds `get_workflow_status_name()` function to return back the workflow status~~
- ~~`pending` status should be transparent to the user, therefore in that case the `queued` status is returned~~
* ~~Modifies `get_workflows()` endpoint to include `pending` workflows if filtered by `queued` status~~
I've tested it by running simple `helloworld` demo and modifying [reana_workflow_engine_serial](https://github.com/reanahub/reana-workflow-engine-serial/blob/b9219f631f327b6e1f45e66dbc1f6c364ce0e973/reana_workflow_engine_serial/tasks.p …

rest: set workflow status to pending after starting the workflow

---

reana_workflow_controller/k8s.py

Closes reanahub/reana-workflow-controller#395

k8s: mount volumes comming from get_workspace_volume instead of shared_volumes

---

reana_workflow_controller/workflow_run_manager.py
requirements.txt
setup.py

closes https://github.com/reanahub/reana-commons/issues/301
To test:
- add `REANA_JOB_CONTROLLER_CONNECTION_CHECK_SLEEP: 5` [here](https://github.com/reanahub/reana/blob/master/helm/reana/values.yaml#L76)
- place wdb breakpoint and inspect `REANA_JOB_CONTROLLER_CONNECTION_CHECK_SLEEP` value [here](https://github.com/reanahub/reana-commons/blob/6d42f9c99d450bd52737959f40bc038fd77cb0fd/reana_commons/utils.py#L388)

workflow_run_manager: propagate job controller connection check env to engines

---

reana_workflow_controller/consumer.py
reana_workflow_controller/workflow_run_manager.py

closes https://github.com/reanahub/reana-job-controller/issues/326
Once the workflow finishes consumer tries to `_delete_workflow_engine_pod()`. Before it was fetching all available pods in the cluster via `current_k8s_corev1_api_client.list_namespaced_pod()` and iterating to find a specific pod to terminate. Now it will fetch the right pod using `label_selector` making it faster to terminate.

consumer: fetch specific workflow pod during deletion

---

reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows.py
reana_workflow_controller/rest/workflows_status.py

- Only query progress information when `include_progress` is set
- Optimize querying the most recent job info
closes #415
closes #416

utils: optimize querying workflow progress information

---

reana_workflow_controller/config.py
reana_workflow_controller/consumer.py

closes https://github.com/reanahub/reana-server/issues/410
As described in https://github.com/reanahub/reana-commons/pull/314#issuecomment-954770879, by default messages in the queue may not spend any time at all and may be consumed straight away. In this case the priority queue will not get any opportunity to prioritize them. 
To illustrate with roofit example. Without the PR all the messages are sent to the consumer (unacked)
With this PR only one message at a time is being processed in the consumer while the others wait in the queue (ready):
Please note that this setting can slow down the job status processing, so we should be careful with selecting the proper value. Perhaps the value should be increased after some initial tests are done.

consumer: set prefetch_count to limit received messages 

---

requirements.txt
setup.py

https://github.com/reanahub/reana-workflow-controller/security/dependabot/requirements.txt/urllib3/open
`requests` [2.25.0](https://github.com/psf/requests/blob/03957eb1c2b9a1e5e6d61f5e930d7c5ed7cfe853/setup.py#L47) vs [2.24.0](https://github.com/psf/requests/blob/0797c61fd541f92f66e409dbf9515ca287af28d2/setup.py#L47), recommended to upgrade to `urllib3>=1.26.5`

setup: upgrade `requests` to fix `urrlib3` vulnerability

---

scripts/generate_openapi_spec.py

closes https://github.com/reanahub/reana-workflow-controller/issues/424
Adds a new line to generated openAPI specs to solve a problem as described in https://github.com/reanahub/reana-commons/pull/330#discussion_r794438980

api: add a new line for generated openapi specs

---

CHANGES.rst
LICENSE
docs/openapi.json
reana_workflow_controller/k8s.py
reana_workflow_controller/version.py
requirements.txt
setup.py
tests/test_views.py
tests/test_workflow_run_manager.py

closes https://github.com/reanahub/reana/issues/482
Tests are failing, most probably, because `reana-commons` is also updated.

Upgrade interactive sessions to support networking.k8s.io/v1 API

---

reana_workflow_controller/workflow_run_manager.py

closes https://github.com/reanahub/reana-workflow-engine-yadage/issues/210
closes https://github.com/reanahub/reana-server/issues/456
Group id for workspace files was set incorrectly, leading to some problems in `recast` demo when `kubernetes_uid` is set to `500` and using `gid` for writing permissions. 
To test add some sleep time [here in recast demo](https://github.com/reanahub/reana-demo-atlas-recast/blob/master/workflow/steps.yml#L13).
Inspect workflow directory:
```
reana ❯ kubectl exec -it reana-run-batch-de475399-ec1f-4dd0-84c4-8680705dfc59-nq59w  -- bash
Defaulted container "workflow-engine" out of: workflow-engine, job-controller
I have no name!@reana-run-batch-de475399-ec1f-4dd0-84c4-8680705dfc59-nq59w:/code$ cd /var/reana/users/00000000-0000-0000-0000-000000000000/workflows/de4 …
```

workflow_run_manager: fix workspace group problem

---

CHANGES.rst
reana_workflow_controller/config.py

addresses reanahub/reana-workflow-controller#436

config: lower job-status-consumer prefetch count

---

reana_workflow_controller/consumer.py

addresses #437 
How to test:
1. Start helloworld workflow - `reana-client run -w test`
2. As soon as workflow starts, wait 3-5 seconds (it should go to the `pending` state) and delete it `reana-client delete -w test`
3. Check `reana-client list`, it will show you that `test` workflow is deleted
4. Check `kubectl get pods`, you will find batch pod in `NotReady` state
5. Check `kubectl logs deployment/reana-workflow-controller job-status-consumer`, you will see that workflow was not in an alive state in DB and logs indicate that. 
```
2022-04-04 11:27:58,215 | root | MainThread | WARNING | Event for not alive workflow 7c081fbc-42b2-4889-841d-a48ccd68dda2 with DB status RunStatus.deleted received:
{"workflow_uuid": "7c081fbc-42b2-4889-841d-a48ccd68dda2", "logs": "", "status": 2, "message": …
```

job-status-consumer: improve logging of "not alive" workflows

---

CHANGES.rst
reana_workflow_controller/rest/utils.py
tests/test_utils.py

Closes reanahub/reana-ui#259
Depends on reanahub/reana-db#168
How to test:
Trying different combinations of `disk` and `cpu` in `WORKFLOW_TERMINATION_QUOTA_UPDATE_POLICY`
1. Launch some workflows
2. Simulate a periodic quota update
```
kubectl create job --from cronjob/reana-resource-quota-update manual-quota-update-001
```
3. Delete one of the workflows, together with its workspace
Expected result: The disk quota is updated immediately after the deletion of a workspace, even if `disk` is not in `WORKFLOW_TERMINATION_QUOTA_UPDATE_POLICY`

rest: update disk usage after workspace deletion

---

CHANGES.rst
reana_workflow_controller/rest/workflows.py

closes https://github.com/reanahub/reana-ui/issues/270
To test:
- Change `termination_update_policy` to `disk,cpu` in [values.yaml](https://github.com/reanahub/reana/blob/master/helm/reana/values.yaml) and redeploy
- Run some workflows (manipulate `quota_used` values in `workflow_resource` db table if needed)
- Verify that sorting works correctly

rest: sort workflow list endpoint by most quota used workflows

---

reana_workflow_controller/consumer.py

closes #451
You cannot test unless it is in production. But I am using precisely the same approach as I have used in https://github.com/reanahub/reana-server/pull/499/files sp it should work fine.

consumer: add pipeline name when reporting Gitlab build status

---

docs/openapi.json
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_workspace.py

Changes the default MIME type used when downloading files to `application/octet-stream`.
Previously, `multipart/form-data` was used but the response was not correctly encoded as such.
Closes reanahub/reana-server#418
How to reproduce the issue:
1. Launch `reana-demo-helloworld`
2. Preview the file `data/names.txt`
3. Check the logs of reana-server
Expected result: the warning is not present anymore in reana-server's logs

rest: change default mime type for files download

---

docs/openapi.json
reana_workflow_controller/rest/workflows.py

After reanahub/reana-server#528, it can happen that workflows do not
have any retention rules.
Closes reanahub/reana#653

rest: allow starting workflows without retention rules

---

.github/workflows/ci.yml
CHANGES.rst
docs/conf.py
docs/openapi.json
reana_workflow_controller/rest/utils.py
reana_workflow_controller/version.py
setup.py

Fixes a problem when calling `delete --include-all-runs` could have deleting other person's workflows by simple name matching.

rest: respect user when deleting all workflow runs

---

CHANGES.rst
reana_workflow_controller/k8s.py
reana_workflow_controller/workflow_run_manager.py

Add new labels for workflow_id, owner_id and workflow_mode for improved subset selection of objects and metadata parsing from the pod specification.
closes https://github.com/reanahub/reana-workflow-controller/issues/498

k8s: update interactive sessions spec to include labels

---

CHANGES.rst
Dockerfile
LICENSE
docs/conf.py

Fixes possible memory consumption trouble on systems like Fedora 37 that use very high file descriptor limits (`fs.nr_open = 1073741816`). See <https://github.com/reanahub/reana/pull/703> for the full explanation.

uwsgi: fix memory consumption related to max-fd

---

docs/openapi.json
reana_workflow_controller/workflow_run_manager.py
requirements.txt
scripts/generate_openapi_spec.py
setup.py

Update to apispec v3, as the version used before is not compatible with
PyYAML v6.
Closes reanahub/reana-commons#399

global: update to apispec v3

---

CHANGES.rst
reana_workflow_controller/workflow_run_manager.py
tests/test_workflow_run_manager.py

Mark the previously running jobs of a stopped workflow as `stopped` in
the database.
Closes reanahub/reana-job-controller#394.

workflow_run_manager: update stopped jobs in the DB

---

reana_workflow_controller/consumer.py

Rollback the database `Session` when an error occurs while handling a
status update message.
This fixes an issue where, if the current transaction fails for any
reason, then the consumer keeps consuming the queue without actually
updating the status of workflows and deleting the related `run-batch`
pods. This is caused by the fact that messages are acknowledged, but
querying the database fails, as the transaction was not rolled back.
This causes REANA to stop scheduling workflows, as finished workflows
are still considered as running.

consumer: rollback database transaction in case of errors

---

CHANGES.rst
Dockerfile
reana_workflow_controller/cli.py

When using the shell form of `CMD`, the provided command is executed
using `/bin/sh -c`, which breaks signal propagation. Use `exec` to
substitute the `sh` process and fix handling of signals by uwsgi.
Also handle SIGTERM in `consume-job-queue` to gracefully stop consuming
the job status queue.
Closes reanahub/reana-job-controller#347

global: fix graceful shutdown

---

reana_workflow_controller/rest/utils.py
setup.py

Change the `delete_workflow` function so that when the deletion of a
workflow includes all its runs, then this is mentioned in the `message`
property returned.
Closes #531.

utils: return different message when deleting all the workflow runs

---

run-tests.sh

Allows execution of selected pytests via PYTESTCMD environment variable. Example: `PYTESTARG="-k test_version" ./run-tests.sh --check-pytest`.
Cleans up running DB container when some pytest segfaults.
Closes reanahub/reana#755.

tests: allow execution of selected pytests only

---

reana_workflow_controller/k8s.py
reana_workflow_controller/workflow_run_manager.py
requirements.txt
setup.py

Closes reanahub/reana-commons#423

k8s: allow automounting of CVMFS repositories

---

CHANGES.rst
reana_workflow_controller/consumer.py

consumer: fix fetching of workflow engine logs when scheduling fails

---

AUTHORS.rst
CHANGES.rst
Dockerfile

"!!! no internal routing support, rebuild with pcre support !!!"

silence uWSGI warning

---

CHANGES.rst
Dockerfile
docs/openapi.json
reana_workflow_controller/version.py
requirements.txt
setup.py

release: 0.9.2

---

Dockerfile

When running development cluster in "latest" mode, install shared
modules in non-editable mode. The editable mode should be reserved only
for development clusters in "debug" mode with the live code reload.

build(docker): install submodules in non-editable mode

---

reana_workflow_controller/rest/utils.py
tests/test_views.py

fix(stop): store engine logs of stopped workflow (#563)

---

reana_workflow_controller/workflow_run_manager.py
requirements.txt
setup.py

Use a valid name when creating a new group with `groupadd`, as numbers
are not valid group names.
Closes #561

fix(manager): use valid group name when calling `groupadd` (#566)

---

reana_workflow_controller/config.py
reana_workflow_controller/k8s.py

feat(k8s): set custom ingressClassName for interactive sessions (#581)

---

AUTHORS.md
reana_workflow_controller/config.py
reana_workflow_controller/k8s.py

Closes reanahub/reana-workflow-controller#587

feat(helm): allow cluster administrator to configure ingress host (#588)

---

reana_workflow_controller/k8s.py
reana_workflow_controller/rest/workflows_session.py
reana_workflow_controller/workflow_run_manager.py
tests/test_k8s.py
tests/test_views.py
tests/test_workflow_run_manager.py

feat(sessions): expose user secrets in interactive sessions (#591)

---

docs/openapi.json
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_status.py
tests/test_views.py

Closes reanahub/reana-client#718

fix(set_workflow_status): validate endpoint arguments (#589)

---

.github/workflows/ci.yml
setup.py

BREAKING CHANGE: drop support for Python 3.6 and 3.7
Closes reanahub/reana#784

build(python): drop support for Python 3.6 and 3.7 (#586)

---

reana_workflow_controller/config.py
reana_workflow_controller/k8s.py
reana_workflow_controller/rest/workflows_session.py
reana_workflow_controller/workflow_run_manager.py
tests/conftest.py
tests/test_views.py
tests/test_workflow_run_manager.py

feat(sessions): add allowlist for interactive session images (#582)

---

Dockerfile

Fix the `JSONArgsRecommended` warning by explicitly setting the shell to
be used when running the Dockerfile's `CMD` command. Note that it is not
possible to switch to the exec form of `CMD`, as it lacks environment
variable expansion.
Closes #596

fix(docker): explicitly specify shell (#598)

---

reana_workflow_controller/consumer.py
reana_workflow_controller/k8s.py
reana_workflow_controller/rest/utils.py
reana_workflow_controller/workflow_run_manager.py
setup.py
tests/test_consumer.py
tests/test_k8s.py
tests/test_views.py
tests/test_workflow_run_manager.py

Closes reanahub/reana-commons#455

refactor(secrets): adapt to reana-commons secret-handling changes (#583)

---

reana_workflow_controller/rest/utils.py

Closes reanahub/reana-server#693

fix(delete_workflow): set retention rules as inactive (#595)

---

AUTHORS.md
docs/openapi.json
reana_workflow_controller/config.py
reana_workflow_controller/factory.py
reana_workflow_controller/rest/workflows.py
reana_workflow_controller/rest/workflows_status.py
reana_workflow_controller/rest/workflows_workspace.py
requirements.txt
setup.py
tests/test_utils.py
tests/test_views.py

| Command               | Allowed   |
|-----------------------|-----------|
| delete            | ❌        |
| diff                | ✅        |
| logs                  | ✅        |
| restart           | ❌        |
| start             | ❌        |
| status              | ✅        |
| stop              | ❌        |
| share-add         | ❌        |
| share-remove      | ❌        |
| share-status      | ❌        |
| close            | ❌        |
| open              | ❌        |
| download            | ✅        |
| du                  | ✅        |
| ls                   | ✅        |
| mv                 | ❌        |
| prune             | ❌        |
| rm              | ❌        |
| upload            | ❌        |
| retention-rules-list| ✅        |
Closes reanahub/reana-server#651, closes …

rest: make details available for shared workflows

---

AUTHORS.md
docs/conf.py
docs/openapi.json
reana_workflow_controller/config.py
reana_workflow_controller/opensearch.py
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_status.py
requirements.txt
setup.py
tests/test_opensearch.py
tests/test_views.py

Optionally fetch live workflow and job logs from OpenSearch.
OpenSearch client is configurable via env variables, passed by Helm chart. Defaults are defined in `config.py` file.
Read the Docs CI builds started to fail, added fix from https://about.readthedocs.com/blog/2024/07/addons-by-default/ in a separate commit.
Related to https://github.com/reanahub/reana/pull/827.

feat(opensearch): fetch logs from opensearch (#602)

---

MANIFEST.in
reana_workflow_controller/config.py
reana_workflow_controller/consumer.py
reana_workflow_controller/dask.py
reana_workflow_controller/k8s.py
reana_workflow_controller/templates/dask_autoscaler.yaml
reana_workflow_controller/templates/dask_cluster.yaml
reana_workflow_controller/workflow_run_manager.py
tests/conftest.py
tests/test_dask.py

This pull request contains the ongoing work of dask integration into REANA.

feat(helm): add initial Dask support

---

reana_workflow_controller/config.py
reana_workflow_controller/consumer.py
reana_workflow_controller/dask.py
tests/test_dask.py

feat(config): make dask autoscaler configurable

---

reana_workflow_controller/k8s.py
reana_workflow_controller/rest/workflows.py

fix(rest): detect session status from the pod state 

---

reana_workflow_controller/consumer.py
reana_workflow_controller/dask.py
reana_workflow_controller/k8s.py
reana_workflow_controller/workflow_run_manager.py

Spawn and delete dask resources inside the kubernetes namespace used by the REANA cluster.
Closes #619

feat(k8s): support custom namespaces for Dask resources

---

reana_workflow_controller/opensearch.py
reana_workflow_controller/rest/utils.py

This PR adds the collection of logs for Dask pods, namely scheduler and workers.
Closes #610

feat(opensearch): capture logs from Dask cluster pods

---

reana_workflow_controller/consumer.py
reana_workflow_controller/dask.py
reana_workflow_controller/k8s.py

fix(k8s): improve error handling for Dask K8s resources

---

reana_workflow_controller/config.py
reana_workflow_controller/dask.py

Before creating the Dask dashboard ingress, the code now checks if either TRAEFIK_ENABLED or TRAEFIK_EXTERNAL is set. This ensures that ingress resources are only created and deleted when Traefik is available.
Closes reanahub/reana#852

fix(dask): check Traefik before creating dashboard ingress

---

reana_workflow_controller/config.py
reana_workflow_controller/consumer.py
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows.py
tests/test_utils.py

This PR is part of harmonizing the treatment of REANA_HOSTNAME accross all REANA components. You can refer to other PRs below.
reanahub/reana#867
reanahub/reana-server#717
Closes reanahub/reana#865

fix(config): set localhost default value for REANA_HOSTNAME

---

reana_workflow_controller/dask.py
reana_workflow_controller/workflow_run_manager.py

We detect if kerberos is necessary for Dask cluster by checking top level kerberos statement under resources field in `reana.yaml`. No additional changes were needed as first implementation of adding kerberos credentials works just fine.
Closes reanahub/reana#871

feat(dask): detect and create kerberos resources for Dask cluster

---

reana_workflow_controller/dask.py
reana_workflow_controller/workflow_run_manager.py
setup.py

We detect if VOMS_proxy is necessary for Dask cluster by checking top level voms_proxy statement under resources field in reana.yaml. Some amendments were needed in order to fetch the secrets from secrets store instead of environment variables since workflow controller does not have access to runtime environment variables just like job controller.
Closes reanahub/reana#872

feat(dask): detect and create VOMS_proxy resources for Dask cluster

---

reana_workflow_controller/config.py

Update reana-auth-vomsproxy to the latest version in order to fix VOMS proxy initialisation troubles for server-side VOMS authentication techniques.
Closes reanahub/reana-auth-vomsproxy#34

fix(config): update reana-auth-vomsproxy to 1.3.1 to fix WLCG IAM

---

reana_workflow_controller/consumer.py
reana_workflow_controller/dask.py
reana_workflow_controller/rest/utils.py
reana_workflow_controller/rest/workflows_status.py
tests/test_views.py

- Mark the Dask service as deleted instead of removing it when the Dask cluster terminates.
- Return the service logs in the response

feat(dask): return service logs and fix service status handling
